name: bodymetrics
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.3
  auto_route: ^10.1.2
  bloc: ^9.0.0
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  fl_chart: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_zoom_drawer: ^3.2.0 

  font_awesome_flutter: ^10.9.1
  get_it: ^8.2.0
  injectable: ^2.5.1
  introduction_screen: ^4.0.0
  json_annotation: ^4.9.0
  logger: ^2.6.1
  lottie: ^3.3.2
  sqflite: ^2.4.2

dev_dependencies:
  auto_route_generator: ^10.2.3
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  json_serializable: ^6.11.1
  very_good_analysis: ^9.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/app_logo/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/profiles/
    - assets/images/onboard/
    - assets/lotties/
    - assets/language/
    - assets/app_logo/app_logo.png

flutter_native_splash:
  color: "#673AB7"
  image: "assets/app_logo/app_logo.png"
  branding_bottom_padding: 24

  android_12:
    image: "assets/app_logo/app_logo.png"
    icon_background_color: "#673AB7"


  web: false